playground/urls.py
from django.urls import path

from . import views
from .views import ReviewCreateView

app_name = "playground"

urlpatterns = [
    path("", views.index, name="index"),
    path("create_review", ReviewCreateView.as_view(), name="review-create"),
]

playground/models.py
from django.db import models
from django.urls import reverse


class Review(models.Model):
    """Review for an app"""

    rating = models.PositiveIntegerField()
    summary = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse("index")

playground/forms.py
from django_starfield import Stars

from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    rating = forms.IntegerField(widget=Stars)

    class Meta:
        model = Review
        fields = ("summary", "rating")

playground/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.edit import CreateView

from .forms import ReviewForm
from .models import Review


def index(request):
    return render(request, "playground/index.html")


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm

playground/templates/playground/base.html
{% load static %}
{% load bootstrap5 %}

<!doctype html>
<html lang="en" class="h-100">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{% static 'appdir/logo.png' %}"/>

        <!-- The page supports both dark and light color schemes,
            and the page author prefers / default is light. -->
        <meta name="color-scheme" content="light dark">

        <!-- Replace the Bootstrap CSS with the Bootstrap-Dark Variant CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.0.1/dist/css/bootstrap-dark.min.css" rel="stylesheet">

        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">

        <title>Playground</title>

    </head>

    <body class="d-flex flex-column h-100">
        <!-- Begin page content -->
        <main class="flex-shrink-0">
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        {% bootstrap_javascript %}
    </body>
</html>

playground/templates/playground/index.html
{% extends "playground/base.html" %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'playground:review-create' %}">Create review</a>
{% endblock %}

playground/templates/playground/review_form.html
{% extends "playground/base.html" %}
{% load bootstrap5 %}

{% block content %}
    <form method="post">{% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Save">
    </form>
{% endblock %}